# Site settings
title: Mi Sitio Web
description: Descripción de mi sitio web
baseurl: /cybercore # Asegúrate de que coincida con la configuración del flujo de trabajo

# Theme settings
theme: jekyll-theme-primer # Puedes cambiar esto según el tema que estés utilizando

# Build settings
markdown: kramdown
permalink: pretty
