swagger: "2.0"
info:
  title: SALUDO DE VUELTA
  version: 1.0.0
paths:
  /cybercore/api/mi-endpoint.php:
    get:
      summary: Obtiene un saludo
      description: Endpoint para obtener un saludo
      responses:
        200:
          description: Respuesta exitosa
          schema:
            type: object
            properties:
              mensaje:
                type: string
