swagger: "2.0"
info:
  title: Documentación de la API de Pedidos para BODEGA
  version: 1.0.0
paths:
  /cybercore/api/pedidosapi_bodega.php/pedidos:
    get:
      summary: Obtener lista de pedidos
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Pedido"
    post:
      summary: Crear un nuevo pedido
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/NuevoPedidoResponse"
        400:
          description: Bad Request

  /cybercore/api/pedidosapi_bodega.php?id={id}:
    get:
      summary: Obtener un pedido específico por su ID
      parameters:
        - name: id
          in: path
          description: ID del pedido a obtener
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Pedido"
        404:
          description: Not Found

definitions:
  Pedido:
    type: object
    properties:
      nombre_origen:
        type: string
      direccion_origen:
        type: string
      celular_origen:
        type: string
      nombre_destino:
        type: string
      direccion_destino:
        type: string
      celular_destino:
        type: string
      obs:
        type: string

  NuevoPedidoResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      codigo_seguimiento:
        type: string
